### ISSUE TITLE
The default project template on flashdevelop doesnt compiles

### ISSUE THREAD

**Issue by rishavs** [hypersurge/awe6#24] opened 2015-11-18 07:16 UTC
I created a new awe6 project in flashdevelop using "awe6 openFl" profile.

Compilation fails for it.
The following error is received:

Building New Project
Running Pre-Build Command Line...
cmd: "C:\HaxeToolkit\haxe/haxelib" run lime build "New Project.xml" neko -debug -Dfdb
C:/HaxeToolkit/haxe/lib/awe6/2,5,732/awe6/extras/gui/Text.hx:155: characters 3-36 : Float should be Null<Int>
C:/HaxeToolkit/haxe/lib/awe6/2,5,732/awe6/extras/gui/Text.hx:155: characters 3-36 : Float should be Int
Build halted with errors.
Done(1)

**Comment by hypersurge** [comment] 2015-11-18 16:00
hi, yep, this is a duplicate of issue 23 with a breaking change coming upstream from OpenFL.

To immediately resolve, patch your copy of awe6.extras.gui.Text line 155 to:

`			_textFormat.size = Math.round( textStyle.size );`

**Comment by rishavs** [comment] 2015-11-19 09:16
Thanks. i didnt see any open bug for this and so opened a new one.

**Comment by hypersurge** [comment] 2015-11-20 02:57
Totally, from here on we won't close an issue until the fix has been released to Haxelib.  I will close this one and reopen #23 as that contains more information.  Thanks.

**Closed by hypersurge** 2015-11-20 02:57 UTC
Labels: duplicate
